export const continents = [
    { value: "Africa", label: "Africa" },
    { value: "Asia", label: "Asia" },
    { value: "Europe", label: "Europe" },
    { value: "North America", label: "North America" },
    { value: "Oceania", label: "Oceania" },
    { value: "South America", label: "South America" },
];

export const countriesPerContinent = {
    Africa: [
        { value: "Algeria", label: "Algeria" },
        { value: "Angola", label: "Angola" },
        { value: "Benin", label: "Benin" },
        { value: "Botswana", label: "Botswana" },
        { value: "Burkina Faso", label: "Burkina Faso" },
        { value: "Burundi", label: "Burundi" },
        { value: "Cameroon", label: "Cameroon" },
        { value: "Cape Verde", label: "Cape Verde" },
        { value: "Central African Republic", label: "Central African Republic" },
        { value: "Chad", label: "Chad" },
        { value: "Comoros", label: "Comoros" },
        { value: "Congo", label: "Congo" },
        { value: "Congo, The Democratic Republic of", label: "Congo, The Democratic Republic of" },
        { value: "Cote d'Ivoire", label: "Cote d'Ivoire" },
        { value: "Djibouti", label: "Djibouti" },
        { value: "Egypt", label: "Egypt" },
        { value: "Equatorial Guinea", label: "Equatorial Guinea" },
        { value: "Eritrea", label: "Eritrea" },
        { value: "Ethiopia", label: "Ethiopia" },
        { value: "Gabon", label: "Gabon" },
        { value: "Gambia", label: "Gambia" },
        { value: "Ghana", label: "Ghana" },
        { value: "Guinea", label: "Guinea" },
        { value: "Guinea-Bissau", label: "Guinea-Bissau" },
        { value: "Kenya", label: "Kenya" },
        { value: "Lesotho", label: "Lesotho" },
        { value: "Liberia", label: "Liberia" },
        { value: "Libyan Arab Jamahiriya", label: "Libyan Arab Jamahiriya" },
        { value: "Madagascar", label: "Madagascar" },
        { value: "Malawi", label: "Malawi" },
        { value: "Mali", label: "Mali" },
        { value: "Mauritania", label: "Mauritania" },
        { value: "Mauritius", label: "Mauritius" },
        { value: "Morocco", label: "Morocco" },
        { value: "Mozambique", label: "Mozambique" },
        { value: "Namibia", label: "Namibia" },
        { value: "Niger", label: "Niger" },
        { value: "Nigeria", label: "Nigeria" },
        { value: "Rwanda", label: "Rwanda" },
        { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
        { value: "Senegal", label: "Senegal" },
        { value: "Seychelles", label: "Seychelles" },
        { value: "Sierra Leone", label: "Sierra Leone" },
        { value: "Somalia", label: "Somalia" },
        { value: "South Africa", label: "South Africa" },
        { value: "South Sudan", label: "South Sudan" },
        { value: "Sudan", label: "Sudan" },
        { value: "Swaziland", label: "Swaziland" },
        { value: "Tanzania, United Republic of", label: "Tanzania, United Republic of" },
        { value: "Togo", label: "Togo" },
        { value: "Tunisia", label: "Tunisia" },
        { value: "Uganda", label: "Uganda" },
        { value: "Western Sahara", label: "Western Sahara" },
        { value: "Zambia", label: "Zambia" },
        { value: "Zimbabwe", label: "Zimbabwe" }
    ],
    Asia: [
        { value: "Afghanistan", label: "Afghanistan" },
        { value: "Armenia", label: "Armenia" },
        { value: "Azerbaijan", label: "Azerbaijan" },
        { value: "Bahrain", label: "Bahrain" },
        { value: "Bangladesh", label: "Bangladesh" },
        { value: "Bhutan", label: "Bhutan" },
        { value: "Brunei Darussalam", label: "Brunei Darussalam" },
        { value: "Cambodia", label: "Cambodia" },
        { value: "China", label: "China" },
        { value: "Georgia", label: "Georgia" },
        { value: "Hong Kong", label: "Hong Kong" },
        { value: "India", label: "India" },
        { value: "Indonesia", label: "Indonesia" },
        { value: "Iran, Islamic Republic of", label: "Iran, Islamic Republic of" },
        { value: "Iraq", label: "Iraq" },
        { value: "Israel", label: "Israel" },
        { value: "Japan", label: "Japan" },
        { value: "Jordan", label: "Jordan" },
        { value: "Kazakstan", label: "Kazakstan" },
        { value: "Korea, Democratic People's Republic of", label: "Korea, Democratic People's Republic of" },
        { value: "Korea, Republic of", label: "Korea, Republic of" },
        { value: "Kuwait", label: "Kuwait" },
        { value: "Kyrgyzstan", label: "Kyrgyzstan" },
        { value: "Lao, People's Democratic Republic", label: "Lao, People's Democratic Republic" },
        { value: "Lebanon", label: "Lebanon" },
        { value: "Macao", label: "Macao" },
        { value: "Malaysia", label: "Malaysia" },
        { value: "Maldives", label: "Maldives" },
        { value: "Mongolia", label: "Mongolia" },
        { value: "Myanmar", label: "Myanmar" },
        { value: "Nepal", label: "Nepal" },
        { value: "Oman", label: "Oman" },
        { value: "Pakistan", label: "Pakistan" },
        { value: "Palestinian Territory, Occupied", label: "Palestinian Territory, Occupied" },
        { value: "Philippines", label: "Philippines" },
        { value: "Qatar", label: "Qatar" },
        { value: "Saudi Arabia", label: "Saudi Arabia" },
        { value: "Singapore", label: "Singapore" },
        { value: "Sri Lanka", label: "Sri Lanka" },
        { value: "Syrian Arab Republic", label: "Syrian Arab Republic" },
        { value: "Taiwan, Province of China", label: "Taiwan, Province of China" },
        { value: "Tajikistan", label: "Tajikistan" },
        { value: "Thailand", label: "Thailand" },
        { value: "Timor-Leste", label: "Timor-Leste" },
        { value: "Turkey", label: "Turkey" },
        { value: "Turkmenistan", label: "Turkmenistan" },
        { value: "United Arab Emirates", label: "United Arab Emirates" },
        { value: "Uzbekistan", label: "Uzbekistan" },
        { value: "Vietnam", label: "Vietnam" },
        { value: "Yemen", label: "Yemen" }
    ],
    Europe: [
        { value: "Aland Islands", label: "Aland Islands" },
        { value: "Albania", label: "Albania" },
        { value: "Andorra", label: "Andorra" },
        { value: "Austria", label: "Austria" },
        { value: "Belarus", label: "Belarus" },
        { value: "Belgium", label: "Belgium" },
        { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
        { value: "Bulgaria", label: "Bulgaria" },
        { value: "Croatia", label: "Croatia" },
        { value: "Cyprus", label: "Cyprus" },
        { value: "Czechia", label: "Czechia" },
        { value: "Denmark", label: "Denmark" },
        { value: "Estonia", label: "Estonia" },
        { value: "Faroe Islands", label: "Faroe Islands" },
        { value: "Finland", label: "Finland" },
        { value: "France", label: "France" },
        { value: "Germany", label: "Germany" },
        { value: "Gibraltar", label: "Gibraltar" },
        { value: "Greece", label: "Greece" },
        { value: "Guernsey", label: "Guernsey" },
        { value: "Holy See (Vatican City State)", label: "Holy See (Vatican City State)" },
        { value: "Hungary", label: "Hungary" },
        { value: "Iceland", label: "Iceland" },
        { value: "Ireland", label: "Ireland" },
        { value: "Isle of Man", label: "Isle of Man" },
        { value: "Italy", label: "Italy" },
        { value: "Jersey", label: "Jersey" },
        { value: "Kosovo", label: "Kosovo" },
        { value: "Latvia", label: "Latvia" },
        { value: "Liechtenstein", label: "Liechtenstein" },
        { value: "Lithuania", label: "Lithuania" },
        { value: "Luxembourg", label: "Luxembourg" },
        { value: "Macedonia, The Former Yugoslav Republic Of", label: "Macedonia, The Former Yugoslav Republic Of" },
        { value: "Malta", label: "Malta" },
        { value: "Moldova, Republic of", label: "Moldova, Republic of" },
        { value: "Monaco", label: "Monaco" },
        { value: "Montenegro", label: "Montenegro" },
        { value: "Netherlands", label: "Netherlands" },
        { value: "Norway", label: "Norway" },
        { value: "Poland", label: "Poland" },
        { value: "Portugal", label: "Portugal" },
        { value: "Republic of Serbia", label: "Republic of Serbia" },
        { value: "Romania", label: "Romania" },
        { value: "Russia Federation", label: "Russia Federation" },
        { value: "San Marino", label: "San Marino" },
        { value: "Slovakia", label: "Slovakia" },
        { value: "Slovenia", label: "Slovenia" },
        { value: "Spain", label: "Spain" },
        { value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen" },
        { value: "Sweden", label: "Sweden" },
        { value: "Switzerland", label: "Switzerland" },
        { value: "Ukraine", label: "Ukraine" },
        { value: "United Kingdom", label: "United Kingdom" }
    ],
    "North America": [
        { value: "Anguilla", label: "Anguilla" },
        { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
        { value: "Aruba", label: "Aruba" },
        { value: "Bahamas", label: "Bahamas" },
        { value: "Barbados", label: "Barbados" },
        { value: "Belize", label: "Belize" },
        { value: "Bermuda", label: "Bermuda" },
        { value: "Bonaire, Sint Eustatius and Saba", label: "Bonaire, Sint Eustatius and Saba" },
        { value: "Canada", label: "Canada" },
        { value: "Cayman Islands", label: "Cayman Islands" },
        { value: "Costa Rica", label: "Costa Rica" },
        { value: "Cuba", label: "Cuba" },
        { value: "Curaçao", label: "Curaçao" },
        { value: "Dominica", label: "Dominica" },
        { value: "Dominican Republic", label: "Dominican Republic" },
        { value: "El Salvador", label: "El Salvador" },
        { value: "Greenland", label: "Greenland" },
        { value: "Grenada", label: "Grenada" },
        { value: "Guadeloupe", label: "Guadeloupe" },
        { value: "Guatemala", label: "Guatemala" },
        { value: "Haiti", label: "Haiti" },
        { value: "Honduras", label: "Honduras" },
        { value: "Jamaica", label: "Jamaica" },
        { value: "Martinique", label: "Martinique" },
        { value: "Mexico", label: "Mexico" },
        { value: "Montserrat", label: "Montserrat" },
        { value: "Nicaragua", label: "Nicaragua" },
        { value: "Panama", label: "Panama" },
        { value: "Puerto Rico", label: "Puerto Rico" },
        { value: "Saint Barthélemy", label: "Saint Barthélemy" },
        { value: "Saint Kitts & Nevis", label: "Saint Kitts & Nevis" },
        { value: "Saint Lucia", label: "Saint Lucia" },
        { value: "Saint Martin", label: "Saint Martin" },
        { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon" },
        { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
        { value: "Sint Maarten", label: "Sint Maarten" },
        { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
        { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
        { value: "United States of America", label: "United States of America" },
        { value: "Virgin Islands, British", label: "Virgin Islands, British" },
        { value: "Virgin Islands, U.S.", label: "Virgin Islands, U.S." }
    ],
    Oceania: [
        { value: "American Samoa", label: "American Samoa" },
        { value: "Australia", label: "Australia" },
        { value: "Christmas Island", label: "Christmas Island" },
        { value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands" },
        { value: "Cook Islands", label: "Cook Islands" },
        { value: "Fiji", label: "Fiji" },
        { value: "French Polynesia", label: "French Polynesia" },
        { value: "Guam", label: "Guam" },
        { value: "Kiribati", label: "Kiribati" },
        { value: "Marshall Islands", label: "Marshall Islands" },
        { value: "Micronesia, Federated States of", label: "Micronesia, Federated States of" },
        { value: "Nauru", label: "Nauru" },
        { value: "New Caledonia", label: "New Caledonia" },
        { value: "New Zealand", label: "New Zealand" },
        { value: "Niue", label: "Niue" },
        { value: "Norfolk Island", label: "Norfolk Island" },
        { value: "Northern Mariana Islands", label: "Northern Mariana Islands" },
        { value: "Palau", label: "Palau" },
        { value: "Papua New Guinea", label: "Papua New Guinea" },
        { value: "Pitcairn", label: "Pitcairn" },
        { value: "Samoa", label: "Samoa" },
        { value: "Solomon Islands", label: "Solomon Islands" },
        { value: "Tokelau", label: "Tokelau" },
        { value: "Tonga", label: "Tonga" },
        { value: "Tuvalu", label: "Tuvalu" },
        { value: "Vanuatu", label: "Vanuatu" },
        { value: "Wallis and Futuna", label: "Wallis and Futuna" }
    ],
    "South America": [
        { value: "Argentina", label: "Argentina" },
        { value: "Bolivia", label: "Bolivia" },
        { value: "Brazil", label: "Brazil" },
        { value: "Chile", label: "Chile" },
        { value: "Colombia", label: "Colombia" },
        { value: "Ecuador", label: "Ecuador" },
        { value: "Falkland Islands (Malvinas)", label: "Falkland Islands (Malvinas)" },
        { value: "French Guiana", label: "French Guiana" },
        { value: "Guyana", label: "Guyana" },
        { value: "Paraguay", label: "Paraguay" },
        { value: "Peru", label: "Peru" },
        { value: "Suriname", label: "Suriname" },
        { value: "Uruguay", label: "Uruguay" },
        { value: "Venezuela", label: "Venezuela" }
    ],
    Antarctica: [
        { value: "Antarctica", label: "Antarctica" },
        { value: "Bouvet Island", label: "Bouvet Island" },
        { value: "French Southern Territories", label: "French Southern Territories" },
        { value: "Heard and Mc Donald Islands", label: "Heard and Mc Donald Islands" },
        { value: "South Georgia & The South Sandwich Islands", label: "South Georgia & The South Sandwich Islands" }
    ]
};
