/**
 * @fileoverview gRPC-Web generated client stub for system_health
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: system_health/system_health.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as system_health_system_health_pb from '../system_health/system_health_pb'; // proto import: "system_health/system_health.proto"


export class SystemHealthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetSystemHealth = new grpcWeb.MethodDescriptor(
    '/system_health.SystemHealthService/GetSystemHealth',
    grpcWeb.MethodType.UNARY,
    system_health_system_health_pb.GetSystemHealthRequest,
    system_health_system_health_pb.GetSystemHealthResponse,
    (request: system_health_system_health_pb.GetSystemHealthRequest) => {
      return request.serializeBinary();
    },
    system_health_system_health_pb.GetSystemHealthResponse.deserializeBinary
  );

  getSystemHealth(
    request: system_health_system_health_pb.GetSystemHealthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<system_health_system_health_pb.GetSystemHealthResponse>;

  getSystemHealth(
    request: system_health_system_health_pb.GetSystemHealthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: system_health_system_health_pb.GetSystemHealthResponse) => void): grpcWeb.ClientReadableStream<system_health_system_health_pb.GetSystemHealthResponse>;

  getSystemHealth(
    request: system_health_system_health_pb.GetSystemHealthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: system_health_system_health_pb.GetSystemHealthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/system_health.SystemHealthService/GetSystemHealth',
        request,
        metadata || {},
        this.methodDescriptorGetSystemHealth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/system_health.SystemHealthService/GetSystemHealth',
    request,
    metadata || {},
    this.methodDescriptorGetSystemHealth);
  }

}

