// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<{[key: string]: any}>;

export function GetSystemInfo():Promise<{[key: string]: string}>;

export function IsOnline():Promise<boolean>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
