/**
 * @fileoverview gRPC-Web generated client stub for debate_management
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: debate_management/debate.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as debate_management_debate_pb from '../debate_management/debate_pb'; // proto import: "debate_management/debate.proto"


export class DebateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRooms = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetRooms',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetRoomsRequest,
    debate_management_debate_pb.GetRoomsResponse,
    (request: debate_management_debate_pb.GetRoomsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetRoomsResponse.deserializeBinary
  );

  getRooms(
    request: debate_management_debate_pb.GetRoomsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetRoomsResponse>;

  getRooms(
    request: debate_management_debate_pb.GetRoomsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetRoomsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetRoomsResponse>;

  getRooms(
    request: debate_management_debate_pb.GetRoomsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetRoomsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetRooms',
        request,
        metadata || {},
        this.methodDescriptorGetRooms,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetRooms',
    request,
    metadata || {},
    this.methodDescriptorGetRooms);
  }

  methodDescriptorGetRoom = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetRoom',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetRoomRequest,
    debate_management_debate_pb.GetRoomResponse,
    (request: debate_management_debate_pb.GetRoomRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetRoomResponse.deserializeBinary
  );

  getRoom(
    request: debate_management_debate_pb.GetRoomRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetRoomResponse>;

  getRoom(
    request: debate_management_debate_pb.GetRoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetRoomResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetRoomResponse>;

  getRoom(
    request: debate_management_debate_pb.GetRoomRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetRoomResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetRoom',
        request,
        metadata || {},
        this.methodDescriptorGetRoom,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetRoom',
    request,
    metadata || {},
    this.methodDescriptorGetRoom);
  }

  methodDescriptorUpdateRoom = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/UpdateRoom',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.UpdateRoomRequest,
    debate_management_debate_pb.UpdateRoomResponse,
    (request: debate_management_debate_pb.UpdateRoomRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.UpdateRoomResponse.deserializeBinary
  );

  updateRoom(
    request: debate_management_debate_pb.UpdateRoomRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.UpdateRoomResponse>;

  updateRoom(
    request: debate_management_debate_pb.UpdateRoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateRoomResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.UpdateRoomResponse>;

  updateRoom(
    request: debate_management_debate_pb.UpdateRoomRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateRoomResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/UpdateRoom',
        request,
        metadata || {},
        this.methodDescriptorUpdateRoom,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/UpdateRoom',
    request,
    metadata || {},
    this.methodDescriptorUpdateRoom);
  }

  methodDescriptorGetJudges = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetJudges',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetJudgesRequest,
    debate_management_debate_pb.GetJudgesResponse,
    (request: debate_management_debate_pb.GetJudgesRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetJudgesResponse.deserializeBinary
  );

  getJudges(
    request: debate_management_debate_pb.GetJudgesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetJudgesResponse>;

  getJudges(
    request: debate_management_debate_pb.GetJudgesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetJudgesResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetJudgesResponse>;

  getJudges(
    request: debate_management_debate_pb.GetJudgesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetJudgesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetJudges',
        request,
        metadata || {},
        this.methodDescriptorGetJudges,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetJudges',
    request,
    metadata || {},
    this.methodDescriptorGetJudges);
  }

  methodDescriptorGetJudge = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetJudge',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetJudgeRequest,
    debate_management_debate_pb.GetJudgeResponse,
    (request: debate_management_debate_pb.GetJudgeRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetJudgeResponse.deserializeBinary
  );

  getJudge(
    request: debate_management_debate_pb.GetJudgeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetJudgeResponse>;

  getJudge(
    request: debate_management_debate_pb.GetJudgeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetJudgeResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetJudgeResponse>;

  getJudge(
    request: debate_management_debate_pb.GetJudgeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetJudgeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetJudge',
        request,
        metadata || {},
        this.methodDescriptorGetJudge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetJudge',
    request,
    metadata || {},
    this.methodDescriptorGetJudge);
  }

  methodDescriptorUpdateJudge = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/UpdateJudge',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.UpdateJudgeRequest,
    debate_management_debate_pb.UpdateJudgeResponse,
    (request: debate_management_debate_pb.UpdateJudgeRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.UpdateJudgeResponse.deserializeBinary
  );

  updateJudge(
    request: debate_management_debate_pb.UpdateJudgeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.UpdateJudgeResponse>;

  updateJudge(
    request: debate_management_debate_pb.UpdateJudgeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateJudgeResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.UpdateJudgeResponse>;

  updateJudge(
    request: debate_management_debate_pb.UpdateJudgeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateJudgeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/UpdateJudge',
        request,
        metadata || {},
        this.methodDescriptorUpdateJudge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/UpdateJudge',
    request,
    metadata || {},
    this.methodDescriptorUpdateJudge);
  }

  methodDescriptorGetPairings = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetPairings',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetPairingsRequest,
    debate_management_debate_pb.GetPairingsResponse,
    (request: debate_management_debate_pb.GetPairingsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetPairingsResponse.deserializeBinary
  );

  getPairings(
    request: debate_management_debate_pb.GetPairingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetPairingsResponse>;

  getPairings(
    request: debate_management_debate_pb.GetPairingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetPairingsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetPairingsResponse>;

  getPairings(
    request: debate_management_debate_pb.GetPairingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetPairingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetPairings',
        request,
        metadata || {},
        this.methodDescriptorGetPairings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetPairings',
    request,
    metadata || {},
    this.methodDescriptorGetPairings);
  }

  methodDescriptorGetPairing = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetPairing',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetPairingRequest,
    debate_management_debate_pb.GetPairingResponse,
    (request: debate_management_debate_pb.GetPairingRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetPairingResponse.deserializeBinary
  );

  getPairing(
    request: debate_management_debate_pb.GetPairingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetPairingResponse>;

  getPairing(
    request: debate_management_debate_pb.GetPairingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetPairingResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetPairingResponse>;

  getPairing(
    request: debate_management_debate_pb.GetPairingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetPairingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetPairing',
        request,
        metadata || {},
        this.methodDescriptorGetPairing,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetPairing',
    request,
    metadata || {},
    this.methodDescriptorGetPairing);
  }

  methodDescriptorUpdatePairings = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/UpdatePairings',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.UpdatePairingsRequest,
    debate_management_debate_pb.UpdatePairingsResponse,
    (request: debate_management_debate_pb.UpdatePairingsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.UpdatePairingsResponse.deserializeBinary
  );

  updatePairings(
    request: debate_management_debate_pb.UpdatePairingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.UpdatePairingsResponse>;

  updatePairings(
    request: debate_management_debate_pb.UpdatePairingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdatePairingsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.UpdatePairingsResponse>;

  updatePairings(
    request: debate_management_debate_pb.UpdatePairingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdatePairingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/UpdatePairings',
        request,
        metadata || {},
        this.methodDescriptorUpdatePairings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/UpdatePairings',
    request,
    metadata || {},
    this.methodDescriptorUpdatePairings);
  }

  methodDescriptorGetBallots = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetBallots',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetBallotsRequest,
    debate_management_debate_pb.GetBallotsResponse,
    (request: debate_management_debate_pb.GetBallotsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetBallotsResponse.deserializeBinary
  );

  getBallots(
    request: debate_management_debate_pb.GetBallotsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetBallotsResponse>;

  getBallots(
    request: debate_management_debate_pb.GetBallotsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetBallotsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetBallotsResponse>;

  getBallots(
    request: debate_management_debate_pb.GetBallotsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetBallotsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetBallots',
        request,
        metadata || {},
        this.methodDescriptorGetBallots,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetBallots',
    request,
    metadata || {},
    this.methodDescriptorGetBallots);
  }

  methodDescriptorGetBallot = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetBallot',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetBallotRequest,
    debate_management_debate_pb.GetBallotResponse,
    (request: debate_management_debate_pb.GetBallotRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetBallotResponse.deserializeBinary
  );

  getBallot(
    request: debate_management_debate_pb.GetBallotRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetBallotResponse>;

  getBallot(
    request: debate_management_debate_pb.GetBallotRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetBallotResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetBallotResponse>;

  getBallot(
    request: debate_management_debate_pb.GetBallotRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetBallotResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetBallot',
        request,
        metadata || {},
        this.methodDescriptorGetBallot,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetBallot',
    request,
    metadata || {},
    this.methodDescriptorGetBallot);
  }

  methodDescriptorUpdateBallot = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/UpdateBallot',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.UpdateBallotRequest,
    debate_management_debate_pb.UpdateBallotResponse,
    (request: debate_management_debate_pb.UpdateBallotRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.UpdateBallotResponse.deserializeBinary
  );

  updateBallot(
    request: debate_management_debate_pb.UpdateBallotRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.UpdateBallotResponse>;

  updateBallot(
    request: debate_management_debate_pb.UpdateBallotRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateBallotResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.UpdateBallotResponse>;

  updateBallot(
    request: debate_management_debate_pb.UpdateBallotRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.UpdateBallotResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/UpdateBallot',
        request,
        metadata || {},
        this.methodDescriptorUpdateBallot,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/UpdateBallot',
    request,
    metadata || {},
    this.methodDescriptorUpdateBallot);
  }

  methodDescriptorGeneratePairings = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GeneratePairings',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GeneratePairingsRequest,
    debate_management_debate_pb.GeneratePairingsResponse,
    (request: debate_management_debate_pb.GeneratePairingsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GeneratePairingsResponse.deserializeBinary
  );

  generatePairings(
    request: debate_management_debate_pb.GeneratePairingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GeneratePairingsResponse>;

  generatePairings(
    request: debate_management_debate_pb.GeneratePairingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GeneratePairingsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GeneratePairingsResponse>;

  generatePairings(
    request: debate_management_debate_pb.GeneratePairingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GeneratePairingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GeneratePairings',
        request,
        metadata || {},
        this.methodDescriptorGeneratePairings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GeneratePairings',
    request,
    metadata || {},
    this.methodDescriptorGeneratePairings);
  }

  methodDescriptorAssignJudges = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/AssignJudges',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.AssignJudgesRequest,
    debate_management_debate_pb.AssignJudgesResponse,
    (request: debate_management_debate_pb.AssignJudgesRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.AssignJudgesResponse.deserializeBinary
  );

  assignJudges(
    request: debate_management_debate_pb.AssignJudgesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.AssignJudgesResponse>;

  assignJudges(
    request: debate_management_debate_pb.AssignJudgesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.AssignJudgesResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.AssignJudgesResponse>;

  assignJudges(
    request: debate_management_debate_pb.AssignJudgesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.AssignJudgesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/AssignJudges',
        request,
        metadata || {},
        this.methodDescriptorAssignJudges,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/AssignJudges',
    request,
    metadata || {},
    this.methodDescriptorAssignJudges);
  }

  methodDescriptorCreateTeam = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/CreateTeam',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.CreateTeamRequest,
    debate_management_debate_pb.Team,
    (request: debate_management_debate_pb.CreateTeamRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.Team.deserializeBinary
  );

  createTeam(
    request: debate_management_debate_pb.CreateTeamRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.Team>;

  createTeam(
    request: debate_management_debate_pb.CreateTeamRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.Team>;

  createTeam(
    request: debate_management_debate_pb.CreateTeamRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/CreateTeam',
        request,
        metadata || {},
        this.methodDescriptorCreateTeam,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/CreateTeam',
    request,
    metadata || {},
    this.methodDescriptorCreateTeam);
  }

  methodDescriptorGetTeam = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetTeam',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetTeamRequest,
    debate_management_debate_pb.Team,
    (request: debate_management_debate_pb.GetTeamRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.Team.deserializeBinary
  );

  getTeam(
    request: debate_management_debate_pb.GetTeamRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.Team>;

  getTeam(
    request: debate_management_debate_pb.GetTeamRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.Team>;

  getTeam(
    request: debate_management_debate_pb.GetTeamRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetTeam',
        request,
        metadata || {},
        this.methodDescriptorGetTeam,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetTeam',
    request,
    metadata || {},
    this.methodDescriptorGetTeam);
  }

  methodDescriptorUpdateTeam = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/UpdateTeam',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.UpdateTeamRequest,
    debate_management_debate_pb.Team,
    (request: debate_management_debate_pb.UpdateTeamRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.Team.deserializeBinary
  );

  updateTeam(
    request: debate_management_debate_pb.UpdateTeamRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.Team>;

  updateTeam(
    request: debate_management_debate_pb.UpdateTeamRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.Team>;

  updateTeam(
    request: debate_management_debate_pb.UpdateTeamRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.Team) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/UpdateTeam',
        request,
        metadata || {},
        this.methodDescriptorUpdateTeam,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/UpdateTeam',
    request,
    metadata || {},
    this.methodDescriptorUpdateTeam);
  }

  methodDescriptorGetTeamsByTournament = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/GetTeamsByTournament',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.GetTeamsByTournamentRequest,
    debate_management_debate_pb.GetTeamsByTournamentResponse,
    (request: debate_management_debate_pb.GetTeamsByTournamentRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GetTeamsByTournamentResponse.deserializeBinary
  );

  getTeamsByTournament(
    request: debate_management_debate_pb.GetTeamsByTournamentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GetTeamsByTournamentResponse>;

  getTeamsByTournament(
    request: debate_management_debate_pb.GetTeamsByTournamentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetTeamsByTournamentResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GetTeamsByTournamentResponse>;

  getTeamsByTournament(
    request: debate_management_debate_pb.GetTeamsByTournamentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GetTeamsByTournamentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/GetTeamsByTournament',
        request,
        metadata || {},
        this.methodDescriptorGetTeamsByTournament,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/GetTeamsByTournament',
    request,
    metadata || {},
    this.methodDescriptorGetTeamsByTournament);
  }

  methodDescriptorDeleteTeam = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/DeleteTeam',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.DeleteTeamRequest,
    debate_management_debate_pb.DeleteTeamResponse,
    (request: debate_management_debate_pb.DeleteTeamRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.DeleteTeamResponse.deserializeBinary
  );

  deleteTeam(
    request: debate_management_debate_pb.DeleteTeamRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.DeleteTeamResponse>;

  deleteTeam(
    request: debate_management_debate_pb.DeleteTeamRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.DeleteTeamResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.DeleteTeamResponse>;

  deleteTeam(
    request: debate_management_debate_pb.DeleteTeamRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.DeleteTeamResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/DeleteTeam',
        request,
        metadata || {},
        this.methodDescriptorDeleteTeam,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/DeleteTeam',
    request,
    metadata || {},
    this.methodDescriptorDeleteTeam);
  }

  methodDescriptorRegeneratePairings = new grpcWeb.MethodDescriptor(
    '/debate_management.DebateService/RegeneratePairings',
    grpcWeb.MethodType.UNARY,
    debate_management_debate_pb.RegeneratePairingsRequest,
    debate_management_debate_pb.GeneratePairingsResponse,
    (request: debate_management_debate_pb.RegeneratePairingsRequest) => {
      return request.serializeBinary();
    },
    debate_management_debate_pb.GeneratePairingsResponse.deserializeBinary
  );

  regeneratePairings(
    request: debate_management_debate_pb.RegeneratePairingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<debate_management_debate_pb.GeneratePairingsResponse>;

  regeneratePairings(
    request: debate_management_debate_pb.RegeneratePairingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GeneratePairingsResponse) => void): grpcWeb.ClientReadableStream<debate_management_debate_pb.GeneratePairingsResponse>;

  regeneratePairings(
    request: debate_management_debate_pb.RegeneratePairingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: debate_management_debate_pb.GeneratePairingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/debate_management.DebateService/RegeneratePairings',
        request,
        metadata || {},
        this.methodDescriptorRegeneratePairings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/debate_management.DebateService/RegeneratePairings',
    request,
    metadata || {},
    this.methodDescriptorRegeneratePairings);
  }

}

