name: Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: pullreminders/assignee-to-reviewer-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # reviewers: "benconte, Josy-coder"
