name: Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: pullreminders/assign-reviewer-action@v1.0.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          reviewers: "benconte, Josy-coder"
